# Copyright (c) 2026 David Reichelt. SPDX-License-Identifier: MIT
PORTNAME     = libvisprof
PORTVERSION  = 0.5.0
MAINTAINER   = David Reichelt
LICENSE      = MIT
SHORT_DESC   = On-screen frame profiler for KallistiOS.
DEPENDENCIES =

GIT_REPOSITORY = https://github.com/freakdave/libvisprof.git
GIT_TAG        = v0.5.0

TARGET         = libvisprof.a
INSTALLED_HDRS = include/visprof/visprof.h
HDR_INSTDIR    = visprof
KOS_DISTFILES  = KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
